OBJ= avntst.o bikck.o bjyck.o blachk.o bspck.o cbeg.o cblat2.o\
cblat3.o cchk12.o cchk13.o cchk22.o cchk23.o cchk32.o cchk33.o\
cchk42.o cchk43.o cchk52.o cchk53.o cchk62.o cchke2.o cchke3.o cchqc.o\
cdf.o cdqag.o cdqagi.o cdqagp.o cdqags.o cdqawc.o cdqawf.o cdqawo.o\
cdqaws.o cdqck.o cdqng.o cfnck.o cgbqc.o cgeck.o cgeqc.o cgtqc.o\
check0.o check1.o check2.o chiqc.o chkxer.o chpqc.o cmake2.o cmake3.o\
cmmch.o cmpare.o cmvch.o comp.o cpbqc.o cpoqc.o cppqc.o cprin.o\
cprpqx.o cptqc.o cqag.o cqagi.o cqagp.o cqags.o cqawc.o cqawf.o\
cqawo.o cqaws.o cqcai.o cqcbh.o cqcbi.o cqcbj.o cqcbk.o cqcby.o cqck.o\
cqng.o cqrqc.o cqrtst.o csiqc.o cspqc.o csvqc.o ctrqc.o davnts.o\
dbeg.o dbikck.o dbjyck.o dblat2.o dblat3.o dbocqx.o dbspck.o dchk12.o\
dchk13.o dchk22.o dchk23.o dchk32.o dchk33.o dchk42.o dchk43.o\
dchk52.o dchk53.o dchk62.o dchke2.o dchke3.o dcmpar.o ddasqc.o ddf.o\
ddjac1.o ddjac2.o ddqck.o ddres1.o ddres2.o dedit2.o deg8ck.o devchk.o\
deverk.o devpck.o df0c.o df0f.o df0o.o df0s.o df0ws.o df1c.o df1f.o\
df1g.o df1n.o df1o.o df1p.o df1s.o df1ws.o df2g.o df2n.o df2o.o df2p.o\
df2s.o df3g.o df3p.o df3s.o df4p.o df4s.o df5s.o dfb.o dfcn1.o dfcn2.o\
dfcn3.o dfcqx.o dfdeqc.o dfdtru.o dfein.o dfill.o dfmat.o dfnck.o\
dfqd1.o dfqd2.o dfztst.o dgeqc.o dgvec.o djac.o dlapqc.o dlseit.o\
dmake2.o dmake3.o dmmch.o dmvch.o dnls1q.o dnsqqk.o dpchq1.o dpchq2.o\
dpchq3.o dpchq4.o dpchq5.o dpfitt.o dplpqx.o dpntck.o dprin.o dqc36j.o\
dqcgls.o dqck.o dqckin.o dqcpsi.o dqfcn2.o dqg8ts.o dqjac2.o dqn79q.o\
drmgen.o dsosfn.o dsosqx.o dsrtqc.o dt0.o dt1.o dt2.o dt3.o dt4.o\
dt5.o dtest.o duivp.o duterr.o duvec.o dxcsrt.o edit2.o eg8ck.o\
eisqx1.o eisqx2.o evchck.o everck.o evpcck.o f0c.o f0f.o f0o.o f0s.o\
f0ws.o f1c.o f1f.o f1g.o f1n.o f1o.o f1p.o f1s.o f1ws.o f2g.o f2n.o\
f2o.o f2p.o f2s.o f3g.o f3p.o f3s.o f4p.o f4s.o f5s.o fb.o fcn1.o\
fcn2.o fcn3.o fcnqx1.o fcnqx2.o fcqx.o fdeqc.o fdtrue.o fein.o fftqx.o\
fmat.o fqd1.o fqd2.o fztest.o gvec.o header.o hsrtqc.o ismpl.o\
isrtqc.o itest.o jac.o lce.o lceres.o lde.o lderes.o lse.o lseiqx.o\
lseres.o outerr.o pass.o pchqk1.o pchqk2.o pchqk3.o pchqk4.o pchqk5.o\
pfitqx.o pntchk.o qc36j.o qc6a.o qcdrc.o qcdrd.o qcdrf.o qcdrj.o\
qcglss.o qckin.o qcpsi.o qcrc.o qcrd.o qcrf.o qcrj.o qg8tst.o qn79qx.o\
qxabm.o qxbdf.o qxblkt.o qxbvsp.o qxcrt.o qxcsp.o qxcyl.o qxdabm.o\
qxdbdf.o qxdbvs.o qxdrkf.o qxgbun.o qxplr.o qxrkf.o qxssp.o rqrtst.o\
sbeg.o sblat2.o sblat3.o sbocqx.o schk12.o schk13.o schk22.o schk23.o\
schk32.o schk33.o schk42.o schk43.o schk52.o schk53.o schk62.o\
schke2.o schke3.o sdasqc.o sdf.o sdjac1.o sdjac2.o sdqck.o sdres1.o\
sdres2.o sfnck.o sgeqc.o slapqc.o smake2.o smake3.o smmch.o smvch.o\
snls1q.o snsqqk.o sosfnc.o sosnqx.o splpqx.o sqck.o sqfcn2.o sqjac2.o\
srmgen.o ssrtqc.o stest.o t0.o t1.o t2.o t3.o t4.o t5.o uivp.o uvec.o\
vfill.o xcsrt.o zqcai.o zqcbh.o zqcbi.o zqcbj.o zqcbk.o zqcby.o

PROGS = test01 test02 test03 test04\
	test05 test06 test07 test08 test09\
	test10 test11 test12 test13 test14\
	test15 test16 test17 test18 test19\
	test20 test21 test22 test23 test24\
	test25 test26 test27 test28 test29\
	test30 test31 test32 test33 test34\
	test35 test36 test37 test38 test39\
	test40 test41 test42 test43 test44\
	test45 test46 test47 test48 test49\
	test50 test51 test52 test53 test54\

#FC = g77
FC = gfortran
FFLAGS = -g -std=legacy
LIB = libslachk.a
SLIB = ../libslatec.a

all: $(PROGS)

clean:
	-$(RM) $(PROGS) $(LIB) $(OBJ) test??.o

$(SLIB):
	$(MAKE) -C ../src

$(LIB): $(OBJ)
	ar r $@ $?
	ranlib $@

test01 : test01.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test02 : test02.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test03 : test03.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test04 : test04.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test05 : test05.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test06 : test06.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test07 : test07.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test08 : test08.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test09 : test09.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test10 : test10.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test11 : test11.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test12 : test12.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test13 : test13.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test14 : test14.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test15 : test15.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test16 : test16.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test17 : test17.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test18 : test18.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test19 : test19.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test20 : test20.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test21 : test21.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test22 : test22.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test23 : test23.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test24 : test24.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test25 : test25.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test26 : test26.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test27 : test27.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test28 : test28.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test29 : test29.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test30 : test30.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test31 : test31.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test32 : test32.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test33 : test33.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test34 : test34.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test35 : test35.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test36 : test36.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test37 : test37.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test38 : test38.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test39 : test39.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test40 : test40.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test41 : test41.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test42 : test42.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

# after 2 have dependency problems...
#
test43 : test43.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec -lslachk

test44 : test44.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec -lslachk

test45 : test45.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test46 : test46.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test47 : test47.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test48 : test48.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test49 : test49.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test50 : test50.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test51 : test51.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test52 : test52.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test53 : test53.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

test54 : test54.o $(LIB) $(SLIB)
	$(FC) -o $@ $< -L. -L../ -lslachk -lslatec

